### ISSUE TITLE
Allow turning off the disabling of controls

### ISSUE THREAD

**Issue by Jitnaught** [justalemon/LemonUI#10]
NativeUI had the [`ControlDisablingEnabled` property](https://github.com/Guad/NativeUI/blob/master/NativeUI/UIMenu.cs#L935), which allowed you to turn off the control disabling entirely so you can handle it yourself. This would be very useful for me in LemonUI.

For example I use this feature from NativeUI in my RopeCreator mod so the Rockstar Editor isn't cancelled when opening the menu. https://gitlab.com/Jitnaught/ropecreator-gta5/-/blob/master/RopeCreator/Menu.cs#L603

**Comment by justalemon** [comment]
> manually disable controls, because NativeUI breaks Rockstar Editor recording when it disables controls

With that comment, I have a couple of ideas in my mind and I'm probably going to end up implementing all of them:

* Adding the `ControlDisablingEnabled` property (probably going to call it just `DisableControls`)
* A list on a property that will keep some controls enabled, as required by the mod developer (`RequiredControls`)
* Keep the Rockstar Editor controls enabled as normal (probably going to need your help with this one)

**Comment by Jitnaught** [comment]
> Keep the Rockstar Editor controls enabled as normal (probably going to need your help with this one)

The only way I could fix it for NativeUI is to use a blacklist for controls instead of a whitelist. Same as LemonUI, NativeUI disables all controls then re-enables some of them. When the Rockstar Editor controls are disabled (i.e. when all controls are disabled) recording gets cancelled. So I had to instead only disable the controls I wanted to.

You can see my blacklist here: https://gitlab.com/Jitnaught/ropecreator-gta5/-/blob/master/RopeCreator/Menu.cs#L13

**Comment by justalemon** [comment]
Done!

Feel free to check the linked commits for more information.
