### ISSUE TITLE
Use SelectedItem as sender parameter for OnActivated?

### ISSUE THREAD

**Issue by Jitnaught** [justalemon/LemonUI#11]
Would using the SelectedItem as the sender parameter for the Activated event make sense?

[Here](https://github.com/justalemon/LemonUI/blob/master/LemonUI/Menus/NativeMenu.cs#L1066) and [here](https://github.com/justalemon/LemonUI/blob/master/LemonUI/Menus/NativeMenu.cs#L997).

If SelectedItem is used for the sender parameter, then you could do something like this in the Activated event:

```csharp
private void OnActivated(object sender, EventArgs e)
{
    if (sender == firstItem)
    {
        //do something
    }
    else if (sender == secondItem)
    {
        //do something else
    }
}
```

With the way it currently works (using the NativeMenu as the sender parameter) you are required to use an event for each individual item.

**Comment by justalemon** [comment]
Fun fact: This was requested multiple times, but nobody wanted to make a proper GitHub issue so I forgot.

**Comment by justalemon** [comment]
Added on 7d0bbaff24c8a28497cdf80cfcd94c5708b089a4
