### ISSUE TITLE
Right Badge position not updating

### ISSUE THREAD

**Issue by jeanropke** [justalemon/LemonUI#13]
When opening a menu with RightBadge, the position is not updated.

Temporarily fix is using Recalculate() after recreating the menu

https://user-images.githubusercontent.com/6243818/116009495-76468800-a5f0-11eb-987d-e382eaa47ffc.mp4

**Comment by justalemon** [comment]
Forgot to mention it: This can be temporarily bypassed by calling Recalculate() after building the menu.

**Comment by justalemon** [comment]
I just saw the source code that you sent to me in Discord more closely.

You are reutilizing one badge element for all menu items, which is not allowed. Every item on the menu needs to have it's own unique badge.
