### ISSUE TITLE
RageMP Support

### ISSUE THREAD

**Issue by TheOfficialDroid** [justalemon/LemonUI#21]
Should be fairly simple to implement; Would fork and implement it myself if I had the time... Mainly recommending this due to RageMP's poor extendibility in the NativeUI Department (Think it actually uses the NativeUI implementation to begin with).

RAGE.Game.Invoker.Invoke<T>( Hash , params[] ); 
RAGE.Game.Invoker.GetReturn<T>()

RAGE.Game.Alignment

```
  public enum Alignment
  {
    Center,
    Left,
    Right,
  }
```

RAGE.Game.Font

```
  public enum Font
  {
    ChaletLondon = 0,
    HouseScript = 1,
    Monospace = 2,
    ChaletComprimeCologne = 4,
    Pricedown = 7,
  }
```

**Comment by TheOfficialDroid** [comment]
Just following up out of interest, has there been any update on reviewing the ability of implementing this?

**Comment by justalemon** [comment]
Yes, it will be done.

RageMP has a lower developer and user adoption than other GTA V frameworks, so I'm trying to prioritize the more highly used platforms instead of those less used.

I have just updated the Milestones, so you can check that to learn in which versions they will be released.

**Comment by justalemon** [comment]
I'm almost done with the RageMP version of LemonUI, I'm just missing some stuff:

* I don't see a class for controlling the gameplay camera, so the RotateCamera property of NativeMenu does nothing
* I don't know how to get output values passed as pointers in 0x6DD8F5AA635EB4B2/_GET_SCRIPT_GFX_POSITION

Those two problems right now just throw NotImplementedException when reached, so I don't forget where they are.

My current progress was pushed in 6d05adc7d60dc067f4c9112ab67c55623d01f380 and ill add what is missing once I get some help (probably from the RageMP Discord Server).

**Comment by TheOfficialDroid** [comment]
> I'm almost done with the RageMP version of LemonUI, I'm just missing some stuff:
> 
> * I don't see a class for controlling the gameplay camera, so the RotateCamera property of NativeMenu does nothing
> * I don't know how to get output values passed as pointers in 0x6DD8F5AA635EB4B2/_GET_SCRIPT_GFX_POSITION
> 
> Those two problems right now just throw NotImplementedException when reached, so I don't forget where they are.
> 
> My current progress was pushed in [6d05adc](https://github.com/justalemon/LemonUI/commit/6d05adc7d60dc067f4c9112ab67c55623d01f380) and ill add what is missing once I get some help (probably from the RageMP Discord Server).

For the second; Possibly returning to an array? The invoker for RageMP is extremely limiting, nor is a lot of the base actually extendable as its locked down, like they don't trust people to know what they're doing.

Just a thought; But I don't think `GET_SCRIPT_GFX_POSITION` is even in their internal enum for natives; I have my own enum of upto date natives for this very reason and invoke via proxy.

**Comment by justalemon** [comment]
> For the second; Possibly returning to an array? The invoker for RageMP is extremely limiting, nor is a lot of the base actually extendable as its locked down, like they don't trust people to know what they're doing.

xday ended up helping me with 0x6DD8F5AA635EB4B2 and how to call it with Invoker.Invoke, now everything is working.

For the RotateCamera property, I ended up calling the natives directly via Invoke (0x743607648ADD4587 for get and 0xB4EC2312F4E5B1F1 for set).

I'm almost done, I just need to push the changes.

**Comment by justalemon** [comment]
Done! Compile the LemonUI.RageMP project to get the assembly that targets RageMP.
