### ISSUE TITLE
Add random

### ISSUE THREAD

**Issue by Quadster** [justalemon/LemonUI#3]
Not really an issue. 

Would be nice if you could set the position of random items added. If you'd like to add items during runtime that is..

**Comment by justalemon** [comment]
You mean something like `NativeMenu.AddItem(NativeItem, int);`? (NativeItem is the item to add, int is the position)

**Comment by Quadster** [comment]
Yes exactly, also does a random add also work for the main menu structure or only within submenus?

**Comment by justalemon** [comment]
You mean the call to `NativeMenu.AddSubMenu`?

**Comment by Quadster** [comment]
No, I meant can you add new options to the main menu during runtime or can you only add to submenus during runtime.

**Comment by justalemon** [comment]
You can freely add and remove items while the menu is visible. Actually, this was one of the main design decisions when creating LemonUI, because NativeUI didn't supported it and it was pissing me off.

**Comment by justalemon** [comment]
![image](https://user-images.githubusercontent.com/11861253/95029021-6fb7e980-067b-11eb-9e6d-8b352bdb7a02.png)
![image](https://user-images.githubusercontent.com/11861253/95029011-59119280-067b-11eb-8318-acc6dc66a7fd.png)

**Comment by Quadster** [comment]
Is there a way to check if an item is Activated after adding it? Even though its params are random every time? 

I.e. id like to input the player each in a new NativeItem, but can't add _Activated as the params are different each time.
