### ISSUE TITLE
Just a TimerBar.

### ISSUE THREAD

**Issue by Quadster** [justalemon/LemonUI#4]
There is no way of just using a TimerBar without menu. Or I am doing something wrong.. I have tried several diffrent approaches before opening the issue. I can use it if I use a collection with inside only the TimerBarProgress, but Visible bool is actually acting weird. 
 
```
   class Bar : Script
    {
        private static float NewProgress = 0f;
        private static readonly ObjectPool pool = new ObjectPool();
        private static readonly TimerBar bar = new TimerBarProgress("Progress") { Progress = NewProgress };

        public Bar()
        {
            pool.Add(bar);
            
            Tick += Bar_Tick;
        }

        private async System.Threading.Tasks.Task Bar_Tick()
        {
            pool.Process();
            if (API.IsPlayerFreeAiming(Game.Player.Character.Handle) == true)
            { NewProgress += 1;  }

        }
    }
```

![image](https://user-images.githubusercontent.com/37592354/96385139-3eb6d900-1192-11eb-878c-36b3ad5f899c.png)

**Comment by justalemon** [comment]
You need to:

* Create a `LemonUI.TimerBars.TimerBarCollection`
* Add the `LemonUI.TimerBars.TimerBar`s onto it
* Add the `LemonUI.TimerBars.TimerBarCollection` into the `LemonUI.ObjectPool`
