### ISSUE TITLE
LemonUI Does not work with SHVDN3

### ISSUE THREAD

**Issue by Winksplorer** [justalemon/LemonUI#41]
I Have Tried Putting it in scripts, referencing the dll, but SHVDN3 still wont recognize LemonUI when running GTA. Can Someone Help Me?

**Comment by justalemon** [comment]
We need the log files (ScriptHookVDotNet.log).

**Comment by Winksplorer** [comment]
Alright.

**Comment by Winksplorer** [comment]
oh i was using a old version now it works
