### ISSUE TITLE
LemonUI Not Recognized by SHVDN3 (Again)

### ISSUE THREAD

**Issue by Winksplorer** [justalemon/LemonUI#42]
So I It Still Occurs, I Do Have Log, But Only From The Console, Hope This Is Enough. and yes, i tried everything i could think of. Please Help Devs!
![GTA5_rT59dr84K1](https://user-images.githubusercontent.com/49623720/132104054-2ff33ce7-79dd-49b9-96f5-1753da3a23f6.png)

**Comment by justalemon** [comment]
You can't compile CS in SHVDN while using 3rd party dependencies. See crosire/scripthookvdotnet#910 for an example.
