### ISSUE TITLE
Add mp_menu_glare

### ISSUE THREAD

**Issue by Oszoou** [justalemon/LemonUI#43]
Add menu glare like in CitizenFX port of NativeUI.

![image](https://user-images.githubusercontent.com/35671020/133450547-3240aae6-a7ce-42c3-8399-5d4440a1ba83.png)

**Comment by WithLithum** [comment]
I do not know if you have already done this but I decompiled mp_menu_glare and found these parameters of SET_DISPLAY_CONFIG function:

- **_screenWidthPixels** - A number, the screen resolution width in pixels (used for calculating)
- **_screenHeightPixels** - A number, the screen resolution height in pixels (used for calculating)
- **_safeTopPercent**, **_safeBottomPercent**, **_safeLeftPercent**, **_safeRightPercent** - A percentage number used for calculation (safezone)
- **_isWideScreen** - Boolean, as it's name to determine whether widescreen
- **_isHiDef** - Boolean
- **_isAsian** - Probably unused (didn't see it in the method body)

**Comment by justalemon** [comment]
> _isWideScreen - Boolean, as it's name to determine whether widescreen

@WithLithum Do you know by any chance what this does exactly?

**Comment by justalemon** [comment]
After playing for a couple of hours, I found that you can't draw the MP_MENU_GLARE scaleform via DRAW_SCALEFORM_MOVIE, only via DRAW_SCALEFORM_MOVIE_FULLSCREEN.

It appears that one of the custom memory patches that FiveM does might have contributed to getting DRAW_SCALEFORM_MOVIE to work as on SP via SHV, you can't use that function with the glare scaleform.

If someone finds a way to draw this scaleform at a custom position, feel free to post a comment here and Ill reopen the issue.
