### ISSUE TITLE
Add Item Tag

### ISSUE THREAD

**Issue by qiangqiang101** [justalemon/LemonUI#5]
```cs
        /// <summary>
        /// Tag Property.
        /// </summary>
        public virtual object Tag { get; set; }
```

**Comment by qiangqiang101** [comment]
Phone contacts...
https://github.com/Bob74/iFruitAddon2

the above link was originated by camxxcore, updated by bob74 but it has issues and the author seems to be MIA, could you maybe fix it?

**Comment by justalemon** [comment]
Can you open a new issue for that one, so we can discuss it separately

Also, one feature request per issue. Please. So we can close them separately once they are implemented.

**Comment by qiangqiang101** [comment]
![@M3SZ1ZS5XSREOI5S8W}U`4](https://user-images.githubusercontent.com/11488961/99121545-8b79bc80-2637-11eb-8618-c860984b62ab.png)
issue is blank space in contact
