### ISSUE TITLE
LemonUI Menu isn't updating real-time when conditions are met.

### ISSUE THREAD

**Issue by HoanGhetti** [justalemon/LemonUI#51]
**NativeItem.Enabled** has an issue where if bool checks are executed, the menu isn't updating real-time in-game.

(e.g.) if (RandomNumber == 1) { GiveSpeedToPed.Enabled = true; } else if (RandomNumber == 0) { GiveSpeedToPed.Enabled = false; }

**Comment by justalemon** [comment]
Can you trigger the item as normal? I want to know if is a visual bug or not.
